defaults:
  - scope:
      path: ""  # This applies to all pages in the root directory
      type: "posts"  # This applies to posts specifically
    values:
      layout: "default"  # Replace with your actual layout name
